export const PROCESS_HOMEPAGE = {
  title: 'Quy trình hoạt động - GreenBoost',
  list_process: [
    { "id": 1, "title_banner": "Tìm kiếm đối tác", "content": "Chúng tôi sẽ tìm kiếm, chọn lọc và đề xuất hợp tác với các doanh nghiệp trong hệ sinh thái các doanh nghiệp phát triển bền vững. Chúng tôi sẽ chủ động tiếp cận các doanh nghiệp này và gửi lời mời hợp tác kinh doanh, hỗ trợ họ quảng bá thương hiệu và đề xuất các chiến lược phân phối sản phẩm phù hợp.", "title": "TÌM KIẾM" },
    { "id": 2, "title_banner": "Đề xuất gói dịch vụ", "content": " Chúng tôi sẽ tạo ra các gói dịch vụ khác nhau để phù hợp với nhu cầu của khách hàng, bao gồm gói 1 năm với mức giá 8.900.000 VNĐ, gói 6 tháng với mức giá 6.900.000 VNĐ và gói 3 tháng với mức giá 3.900.000 VNĐ. Các gói này sẽ bao gồm các dịch vụ như tư vấn marketing, tư vấn chiến lược, phân tích thị trường, quảng cáo trực tuyến, thiết kế trang web, cung cấp nội dung và hỗ trợ khách hàng.", "title": "Gói dịch vụ" },
    { "id": 3, "title_banner": "Tìm kiếm đối tác", "content": "Chúng tôi sẽ tìm kiếm, chọn lọc và đề xuất hợp tác với các doanh nghiệp trong hệ sinh thái các doanh nghiệp phát triển bền vững. Chúng tôi sẽ chủ động tiếp cận các doanh nghiệp này và gửi lời mời hợp tác kinh doanh, hỗ trợ họ quảng bá thương hiệu và đề xuất các chiến lược phân phối sản phẩm phù hợp.","title": "Truyền thông" },
    { "id": 4, "title_banner": "Tìm kiếm đối tác", "content": "Chúng tôi sẽ tìm kiếm, chọn lọc và đề xuất hợp tác với các doanh nghiệp trong hệ sinh thái các doanh nghiệp phát triển bền vững. Chúng tôi sẽ chủ động tiếp cận các doanh nghiệp này và gửi lời mời hợp tác kinh doanh, hỗ trợ họ quảng bá thương hiệu và đề xuất các chiến lược phân phối sản phẩm phù hợp.", "title": "Cộng đồng" },
    { "id": 5, "title_banner": "Tìm kiếm đối tác", "content": "Chúng tôi sẽ tìm kiếm, chọn lọc và đề xuất hợp tác với các doanh nghiệp trong hệ sinh thái các doanh nghiệp phát triển bền vững. Chúng tôi sẽ chủ động tiếp cận các doanh nghiệp này và gửi lời mời hợp tác kinh doanh, hỗ trợ họ quảng bá thương hiệu và đề xuất các chiến lược phân phối sản phẩm phù hợp.", "title": "Tư vấn & Hỗ trợ" },
    { "id": 6, "title_banner": "Tìm kiếm đối tác", "content": "Chúng tôi sẽ tìm kiếm, chọn lọc và đề xuất hợp tác với các doanh nghiệp trong hệ sinh thái các doanh nghiệp phát triển bền vững. Chúng tôi sẽ chủ động tiếp cận các doanh nghiệp này và gửi lời mời hợp tác kinh doanh, hỗ trợ họ quảng bá thương hiệu và đề xuất các chiến lược phân phối sản phẩm phù hợp.",  "title": "Đánh giá" }
  ]
} 
// "find", "services", "media", "community", "support", "evaluate"